### ISSUE TITLE
Lineto.com Circular font can be downloaded for free

### ISSUE THREAD

**Issue by rwoody** [aliyarahman/d3samples#1]
I believe some fonts included in the repo are licensed/not free fonts and are easily downloadable for someone not wanting to pay for them.

Reference: [https://lineto.com/The+Fonts/All+Fonts/Circular/](https://lineto.com/The+Fonts/All+Fonts/Circular/)

**Comment by aliyarahman** [comment]
Thanks for catching that - I'll remove asap (:
